#!/usr/bin/env python3
"""The 白い熊 画 カメラ launcher icon (variant "b — camera body", chosen by 白い熊 2026-09-28).

A camera outline — body, viewfinder hump, flash dot — drawn as yellow strokes, with our traced 画
(kaku-notification.svg, trace-icon.py --style glyph) on its front, on black. Written as
shiroikuma/icon/kaku-camera-icon.svg; gen-icons.py renders the Android resources from the same
numbers (CAMERA_PATH, FLASH, GLYPH below), so the two never drift apart.

Usage: python3 shiroikuma/icon/camera-icon.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GLYPH_SVG = os.path.join(ROOT, "shiroikuma/icon/kaku-notification.svg")
OUT = os.path.join(ROOT, "shiroikuma/icon/kaku-camera-icon.svg")

YELLOW = "#FFFF00"
CAMERA_PATH = ("M22,44 a7,7 0 0 1 7,-7 H40 L44.5,30 H63.5 L68,37 H79 a7,7 0 0 1 7,7 V76 "
               "a7,7 0 0 1 -7,7 H29 a7,7 0 0 1 -7,-7 Z")
CAMERA_STROKE = 2.2
FLASH = (77.5, 45, 2.0)            # cx, cy, r
GLYPH = (54, 60, 31)               # centre x, centre y, size in the 108 viewport
GLYPH_SRC_SIZE = 60.3              # the glyph's size inside kaku-notification.svg
GLYPH_SRC_CENTRE = 54.0


def glyph_inner():
    src = open(GLYPH_SVG, encoding="utf-8").read()
    return src[src.index('<g transform="translate('):src.rindex("</svg>")]


def glyph_transform():
    cx, cy, size = GLYPH
    s = size / GLYPH_SRC_SIZE
    return cx - s * GLYPH_SRC_CENTRE, cy - s * GLYPH_SRC_CENTRE, s


def main():
    tx, ty, s = glyph_transform()
    fx, fy, fr = FLASH
    open(OUT, "w", encoding="utf-8").write(f'''<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" viewBox="0 0 108 108">
  <!-- 白い熊 画 カメラ launcher icon. Generated by shiroikuma/icon/camera-icon.py — edit that, not this file. -->
  <rect width="108" height="108" fill="#000000"/>
  <path d="{CAMERA_PATH}" fill="none" stroke="{YELLOW}" stroke-width="{CAMERA_STROKE}" stroke-linejoin="round"/>
  <circle cx="{fx}" cy="{fy}" r="{fr}" fill="{YELLOW}"/>
  <g transform="translate({tx:.3f},{ty:.3f}) scale({s:.5f})">{glyph_inner()}</g>
</svg>
''')
    print(f">>> {OUT}")


if __name__ == "__main__":
    main()
