#!/usr/bin/env python3
"""Render every icon resource of 白い熊 画 from the traced SVGs in shiroikuma/icon/.

  kaku-icon.svg          (trace-icon.py --style tile)   → the launcher icon
  kaku-notification.svg  (trace-icon.py --style glyph)  → the status-bar icon (画 alone reads at 24 dp)

Written into app/src/main/res, replacing upstream's:

  mipmap-anydpi-v26/ic_launcher.xml, ic_launcher_round.xml   adaptive icon: black ground, yellow
                                                             foreground, monochrome themed-icon layer
  drawable/ic_kaku_foreground.xml, ic_kaku_monochrome.xml    the adaptive layers (vectors)
  mipmap-*dpi/ic_launcher.png                                legacy launcher, rounded square
  mipmap-*dpi/ic_launcher_round.png                          legacy round launcher
  drawable/kaku_notification_icon.xml                        status-bar small icon (white alpha mask)
  values/colors_kaku_icon.xml                                the icon ground colour
  shiroikuma/icon/kaku-icon-512.png                          for the README / releases

Needs rsvg-convert and magick. Usage: python3 shiroikuma/icon/gen-icons.py
"""
import os
import re
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ICON_SVG = os.path.join(ROOT, "shiroikuma/icon/kaku-icon.svg")
NOTIF_SVG = os.path.join(ROOT, "shiroikuma/icon/kaku-notification.svg")
RES = os.path.join(ROOT, "app/src/main/res")
YELLOW, BLACK = "#FFFF00", "#000000"
HEADER = "<!-- Generated by shiroikuma/icon/gen-icons.py from shiroikuma/icon/*.svg — do not edit. -->"
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def write(rel, text):
    path = os.path.join(RES, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write(text)
    print(f">>> {path}")


def parse(svg_path):
    svg = open(svg_path, encoding="utf-8").read()
    groups = re.findall(r'<g transform="([^"]+)"', svg)
    ox, oy, k = map(float, re.match(r"translate\(([-\d.]+),([-\d.]+)\) scale\(([-\d.]+)\)", groups[0]).groups())
    th = float(re.match(r"translate\([-\d.]+,([-\d.]+)\)", groups[1]).group(1))
    paths = re.findall(r'<path d="([^"]+)"', svg)
    cw, ch = (108 - 2 * ox) / k, (108 - 2 * oy) / k
    return paths, th, cw, ch, k


def vector(svg_path, color, size_dp, fill=None, viewport=108):
    """The traced mark as a VectorDrawable; its larger side `fill` viewport units (default: as traced)."""
    paths, th, cw, ch, k = parse(svg_path)
    if fill is None:
        fill = max(cw, ch) * k
    kk = fill / max(cw, ch)
    tx, ty = (viewport - cw * kk) / 2, (viewport - ch * kk) / 2
    body = "\n".join(f'            <path android:fillColor="{color}" android:fillType="evenOdd"\n'
                     f'                android:pathData="{p}" />' for p in paths)
    return f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
    <group android:translateX="{tx:.4f}" android:translateY="{ty:.4f}"
        android:scaleX="{kk:.6f}" android:scaleY="{kk:.6f}">
        <group android:translateY="{th}" android:scaleX="0.1" android:scaleY="-0.1">
{body}
        </group>
    </group>
</vector>
'''


def main():
    write("drawable/ic_kaku_foreground.xml", vector(ICON_SVG, YELLOW, 108))
    write("drawable/ic_kaku_monochrome.xml", vector(ICON_SVG, BLACK, 108))
    write("drawable/kaku_notification_icon.xml", vector(NOTIF_SVG, "#FFFFFF", 24, fill=96))
    write("values/colors_kaku_icon.xml", f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<resources>
    <color name="kaku_icon_background">{BLACK}</color>
</resources>
''')
    adaptive = f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/kaku_icon_background" />
    <foreground android:drawable="@drawable/ic_kaku_foreground" />
    <monochrome android:drawable="@drawable/ic_kaku_monochrome" />
</adaptive-icon>
'''
    write("mipmap-anydpi-v26/ic_launcher.xml", adaptive)
    write("mipmap-anydpi-v26/ic_launcher_round.xml", adaptive)

    with tempfile.TemporaryDirectory() as tmp:
        master = os.path.join(tmp, "master.png")
        subprocess.run(["rsvg-convert", "-w", "1024", "-h", "1024", ICON_SVG, "-o", master], check=True)

        def masked(size, out, round_):
            os.makedirs(os.path.dirname(out), exist_ok=True)
            mask = os.path.join(tmp, "mask.png")
            shape = (f"circle {size / 2 - 0.5},{size / 2 - 0.5} {size / 2 - 0.5},0" if round_
                     else f"roundrectangle 0,0,{size - 1},{size - 1},{int(size * 0.225)},{int(size * 0.225)}")
            subprocess.run(["magick", "-size", f"{size}x{size}", "xc:black", "-fill", "white", "-draw", shape, mask],
                           check=True)
            subprocess.run(["magick", master, "-resize", f"{size}x{size}", mask, "-alpha", "off",
                            "-compose", "CopyOpacity", "-composite", out], check=True)
            print(f">>> {out}")

        for d, size in DENSITIES.items():
            masked(size, os.path.join(RES, f"mipmap-{d}/ic_launcher.png"), False)
            masked(size, os.path.join(RES, f"mipmap-{d}/ic_launcher_round.png"), True)
        masked(512, os.path.join(ROOT, "shiroikuma/icon/kaku-icon-512.png"), False)


if __name__ == "__main__":
    main()
