#!/usr/bin/env python3
"""Trace the 白い熊 画 launcher icon from upstream Kaku's artwork.

Source: shiroikuma/icon/kaku-upstream-512.png (upstream's app/src/main/ic_launcher-web.png) — 512 px store icon, a white rounded tile with a
black 画. Nothing is drawn freehand: every shape comes out of that raster, re-drawn in the house
black-yellow style (yellow on a black ground). Styles:

  tile     the tile's silhouette becomes a yellow outline, 画 stays a solid yellow shape (default);
  glyph    画 alone, as a solid yellow shape, drawn larger;
  outline  画 alone, as yellow line-art (every stroke outlined).

The mask is vectorised with potrace and written as an SVG on the 108×108 adaptive-icon viewport
(black ground). shiroikuma/icon/gen-icons.py renders every resource from shiroikuma/icon/kaku-icon.svg.

Usage: python3 shiroikuma/icon/trace-icon.py [--style tile|glyph|outline] [--out FILE] [--debug DIR]
"""
import argparse
import os
import re
import subprocess
import tempfile

import numpy as np
from PIL import Image
from scipy import ndimage as ndi

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "shiroikuma/icon/kaku-upstream-512.png")   # upstream's app/src/main/ic_launcher-web.png
OUT = os.path.join(ROOT, "shiroikuma/icon/kaku-icon.svg")

SCALE = 4                 # 512 px → 2048 px before tracing
YELLOW, BLACK = "#FFFF00", "#000000"
# The mark's larger side, fraction of the 108-unit viewport; the tile's corners must stay inside
# the 72-unit safe zone (radius 36 around the centre).
MARK = {"tile": 0.62, "glyph": 0.56, "outline": 0.58}
STROKE = {"tile": 0.022, "outline": 0.012}   # outline width, fraction of the canvas


def disk(r):
    r = max(1, int(round(r)))
    y, x = np.ogrid[-r:r + 1, -r:r + 1]
    return x * x + y * y <= r * r


def largest(mask):
    lab, n = ndi.label(mask)
    if n == 0:
        return mask
    sizes = ndi.sum(mask, lab, range(1, n + 1))
    return lab == (1 + int(np.argmax(sizes)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--style", choices=sorted(MARK), default="tile")
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--debug", help="write the intermediate masks as PNGs into this directory")
    args = ap.parse_args()

    im = Image.open(SRC).convert("RGBA")
    w, h = im.size
    im = im.resize((w * SCALE, h * SCALE), Image.LANCZOS)
    px = np.asarray(im).astype(np.float32) / 255.0
    r, g, b, a = px[..., 0], px[..., 1], px[..., 2], px[..., 3]
    size = im.size[0]
    lum = 0.299 * r + 0.587 * g + 0.114 * b

    # The tile: opaque and near-white — the soft grey drop shadow below it falls out.
    tile = ndi.binary_fill_holes(largest((a > 0.9) & (lum > 0.9) | (a > 0.9) & (lum < 0.5)))
    tile = ndi.binary_opening(tile, disk(SCALE * 2))
    tile = ndi.gaussian_filter(tile.astype(np.float32), SCALE * 1.5) > 0.5
    # 画: the dark strokes inside the tile.
    glyph = (a > 0.5) & (lum < 0.5) & ndi.binary_erosion(tile, disk(SCALE * 4))
    glyph = ndi.gaussian_filter(glyph.astype(np.float32), SCALE * 0.6) > 0.5

    if args.style == "tile":
        sw = STROKE["tile"] * size
        art = (tile & ~ndi.binary_erosion(tile, disk(sw))) | glyph
    elif args.style == "glyph":
        art = glyph
    else:
        sw = STROKE["outline"] * size
        art = glyph & ~ndi.binary_erosion(glyph, disk(sw))

    if args.debug:
        os.makedirs(args.debug, exist_ok=True)
        for name, m in dict(tile=tile, glyph=glyph, art=art).items():
            Image.fromarray((m * 255).astype(np.uint8)).save(os.path.join(args.debug, f"{name}.png"))

    # potrace: black = foreground in a PBM.
    ys, xs = np.nonzero(art)
    x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
    crop = art[y0:y1, x0:x1]
    with tempfile.TemporaryDirectory() as tmp:
        pbm = os.path.join(tmp, "art.pbm")
        Image.fromarray(((~crop) * 255).astype(np.uint8)).convert("1").save(pbm)
        svg = subprocess.run(["potrace", "-s", "--flat", "-a", "1.0", "-O", "0.4", "-t", "8", "-o", "-", pbm],
                             check=True, capture_output=True, text=True).stdout

    tr = re.search(r'<g transform="([^"]+)"', svg).group(1)
    paths = re.findall(r'<path d="([^"]+)"', svg, re.S)
    cw, ch = crop.shape[1], crop.shape[0]
    k = 108 * MARK[args.style] / max(cw, ch)
    ox, oy = (108 - cw * k) / 2, (108 - ch * k) / 2
    body = "\n".join(f'    <path d="{" ".join(p.split())}"/>' for p in paths)
    open(args.out, "w").write(f'''<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" viewBox="0 0 108 108">
  <!-- 白い熊 画 launcher icon ({args.style}): upstream Kaku's 画 tile (shiroikuma/icon/kaku-upstream-512.png)
       traced in the house black-yellow style. Generated by shiroikuma/icon/trace-icon.py — edit that,
       not this file. -->
  <rect width="108" height="108" fill="{BLACK}"/>
  <g transform="translate({ox:.3f},{oy:.3f}) scale({k:.6f})">
   <g transform="{tr}" fill="{YELLOW}" fill-rule="evenodd">
{body}
   </g>
  </g>
</svg>
''')
    print(f">>> {args.out} ({len(paths)} paths, mark {cw}x{ch} px)")


if __name__ == "__main__":
    main()
